ROUTINE ExercicoObjeto3
ExercicoObjeto3 ;
    Kill ^Treinamento.Data.TurmaD
	Set nomex = "Chico|Felipe|Jose"
    Set turma = ##class(Treinamento.Data.Turma).%New()
    Set turma.Curso.Nome = "Fisica Nuclear"
    Set turma.DataInicio = "19/10/2024"
    Set turma.Instrutor = "Pedro"
	For i=1:1:3 {
        Set oAlunos=##class(Treinamento.Data.Aluno).%OpenId(i)
		Do turma.Alunos.SetAt(oAlunoslunos)
    }
    Set Status = turma.%Save()
    Quit